{"data": [{"type": "report", "id": 1, "attributes": {"environment": {"Python": "3.9.1", "Platform": "Windows-10-10.0.19041-SP0"}, "summary": {"failed": 1, "num_tests": 1, "duration": 171.01735401153564}, "created_at": "2021-05-20 12:20:02.271516"}, "relationships": {"tests": {"data": [{"id": 1, "type": "test"}]}}}], "included": [{"id": 1, "type": "test", "attributes": {"name": "PmaxTests/Android/DailyRun_Test.py::Basic_Sanity_Checks::test_Pax_Payment_VisaCredit_CNP_Success", "duration": 178.27020829999998, "run_index": 0, "setup": {"name": "setup", "duration": 9.459355599999999, "outcome": "passed"}, "call": {"name": "call", "duration": 159.3070632, "outcome": "failed", "longrepr": "self = <[RecursionError('maximum recursion depth exceeded') raised in repr()] Basic_Sanity_Checks object at 0x1f625c902e0>\n\n    @pytest.mark.SanityChecks\n    def test_Pax_Payment_VisaCredit_CNP_Success(self):\n    \n        TestHelpers.PAX_Terminal_Activation(self)\n        self.logger.info(\"App opened successfully\")\n        Dojo.click(self, SaleScreen.BUTTON_ONE)\n        Dojo.click(self, SaleScreen.BUTTON_FIVE)\n        Dojo.click(self, SaleScreen.BUTTON_ZERO)\n        Dojo.click(self, SaleScreen.BUTTON_FIVE)\n        self.logger.info(\"entered \u00a305.05 pounds transaction\")\n        Dojo.click(self, SaleScreen.BUTTON_CONFIRM)\n        PaymentStatus = TestHelpers.Pax_CNP_Transactions_temp(\n            self, 'visa credit')\n>       Dojo.assert_boolean(PaymentStatus, expected=True)\n\nPmaxTests\\Android\\DailyRun_Test.py:83: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual = False, expected = True\n\n    @staticmethod\n    def assert_boolean(actual, expected=True):\n>       assert actual == expected\nE       AssertionError\n\nHelpers\\DriverUtils.py:317: AssertionError", "log": "INFO     conftest:AppiumDriver.py:39 Configuring desired capabilities\nINFO     conftest:AppiumDriver.py:55 Appium web driver initialized.\nINFO     conftest:TestCase_Helpers.py:97 Pax activation has completed\nINFO     conftest:TestCase_Helpers.py:105 com.dojo.pax.main.MainActivity\nINFO     conftest:DailyRun_Test.py:74 App opened successfully\nINFO     conftest:DailyRun_Test.py:79 entered \u00a305.05 pounds transaction\nINFO     conftest:TestCase_Helpers.py:171 Visa Credit CNP started!\nERROR    conftest:DriverUtils.py:244 assert_text failed attempt 1- ('id', 'com.pax.poslink.staging.debug:id/title')\nERROR    conftest:TestCase_Helpers.py:316 CNP Payment Failed. Hence, unable to continue test casetest_Pax_Payment_VisaCredit_CNP_Success\nERROR    conftest:AppiumDriver.py:78 Taking screenshot on failure\nINFO     conftest:AppiumDriver.py:68 Appium Driver closed."}, "teardown": {"name": "teardown", "duration": 0.04443390000000136, "outcome": "passed"}, "outcome": "failed"}}]}